@host=localhost
@port= 4000


### Login
POST http://{{host}}:{{port}}/auth/login
Content-Type: application/json

{
    "email": "jwt@gmail.com",
    "password": "julie"
    
}


### Register
POST http://{{host}}:{{port}}/auth/signin
Content-Type: application/json

{
    "email": "jwt@gmail.com",
    "password": "julie"
    
}