@host=localhost
@port=4000

### Get all the received messages of the connected user
GET http://{{host}}:{{port}}/messages/1

### Get all the sent messages from the connected user to someone 
GET http://{{host}}:{{port}}/messages/{userId}/sent/{senderId}
GET http://{{host}}:{{port}}/messages/5/sent

### Get all the received messages of the connected user written by someone
GET http://{{host}}:{{port}}/messages/{userId}/received/{senderId}
GET http://{{host}}:{{port}}/messages/5/received/4


### create one message
POST http://{{host}}:{{port}}/messages/
Content-Type: application/json

{
  "content": "Lorem ipsum dolor sit fsd fdg gfdhfgh .",
  "status": true,
  "authorProfileId": 2,
  "targetProfileId": 1
  
}


