@host=localhost
@port=4000

### Get profiles
GET http://{{host}}:{{port}}/profiles

### Get one profile
GET http://{{host}}:{{port}}/profiles/{profile_id}

### Get the profile 3
GET http://{{host}}:{{port}}/profiles/3

### Update a profile
PUT http://{{host}}:{{port}}/profiles/{profile_id}

###
PATCH http://{{host}}:{{port}}/profiles/3
Content-Type: application/json

{
	"firstname": "Jacqueline"
}

### Delete a profile
DELETE http://{{host}}:{{port}}/profiles/{profile_id}

### Delete the profile 3
DELETE http://{{host}}:{{port}}/profiles/3

