@host=localhost
@port=4000

### Get users
GET http://{{host}}:{{port}}/users

### Get a user
GET http://{{host}}:{{port}}/users/{userId}

### Get the user 2
GET http://{{host}}:{{port}}/users/2

### Create a user
POST http://{{host}}:{{port}}/users
Content-Type: application/json

{
    "email": "jacqueline@gmail.com",
    "password": "jacoquine",
    "role": "admin"
}

### Update a user
PUT http://{{host}}:{{port}}/users/{userId}

### Create a profile
POST http://{{host}}:{{port}}/users/9/profile
Content-Type: application/json

{
    "firstname": "Yvette",
    "lastname": "PETIT",
    "birthdate": "1958/03/20",
    "gender": "femme",
    "location": "Marseille",
    "bio": "",
    "status": false,
    "avatar": ""
}

### Update a user
PATCH http://{{host}}:{{port}}/users/9
Content-Type: application/json

{
	"role": "user"
}

### Delete a user
DELETE http://{{host}}:{{port}}/users/{userId}

### Delete the user 3
DELETE http://{{host}}:{{port}}/users/16


### Login
POST http://{{host}}:{{port}}/users/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password",
    
}