@host=localhost
@port=4000

### Récupérer les users
GET http://{{host}}:{{port}}/users


### Récupérer un user
GET http://{{host}}:{{port}}/users/{userId}

### Récupérer le user 2
GET http://{{host}}:{{port}}/users/2


### Créer un user
POST http://{{host}}:{{port}}/users
Content-Type: application/json

{
    "email": "jacqueline.r@gmail.com",
    "password": "jacoquine",
    "role": "admin"
}

### Modifier un user
PATCH http://{{host}}:{{port}}/users/{userId}

### Modifier un user
PATCH http://{{host}}:{{port}}/users/12
Content-Type: application/json

{
	"role": "user"
}


### Supprimer un user
DELETE http://{{host}}:{{port}}/users/{userId}

### Supprimer le user 3
DELETE http://{{host}}:{{port}}/users/12

### Créer un profil
POST http://{{host}}:{{port}}/users/{userId}/profile
### Créer un profil
POST http://{{host}}:{{port}}/users/13/profile
Content-Type: application/json

{
    "firstname": "Yvette",
    "lastname": "PETIT",
    "birthdate": "1958/03/20",
    "gender": "femme",
    "location": "Marseille",
    "bio": "",
    "status": false,
    "avatar": ""
}