BEGIN;

DROP TABLE IF EXISTS "user", "profile", "event", "interest";

CREATE TABLE "user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "email" VARCHAR(255) UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(255) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "profile" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "firstname" VARCHAR(255) NOT NULL,
    "lastname" VARCHAR(255) NOT NULL,
    "birthdate" DATE NOT NULL,
    "gender" VARCHAR(50) NOT NULL,
    "location" VARCHAR(255) NOT NULL,
    "bio" VARCHAR(255),
    "status" VARCHAR(255) NOT NULL,
    "avatar" VARCHAR(255),
    "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "event" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "location" VARCHAR(255) NOT NULL,
    "date" DATE NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    "published" BOOLEAN NOT NULL,
    "maxnumberpeople" integer,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "interest" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" VARCHAR(255) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "profile_participate_to_event" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "profile_id" integer NOT NULL REFERENCES "profile"("id"),
    "event_id" integer NOT NULL REFERENCES "event"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "profile_has_interest" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "profile_id" integer NOT NULL REFERENCES "profile"("id"),
    "interest_id" integer NOT NULL REFERENCES "interest"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "message" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content" TEXT NOT NULL,
    "status" BOOLEAN NOT NULL,
    "author_profile_id" integer NOT NULL REFERENCES "profile"("id"),
    "target_profile_id" integer NOT NULL REFERENCES "profile"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

COMMIT;